#
# Copyright (C) 2025 TeamVoxelOdyssey
#
# This file is part of VoxelOdysseyPlugins.
#
# VoxelOdysseyPlugins is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# VoxelOdysseyPlugins is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with VoxelOdysseyPlugins. If not, see <https://www.gnu.org/licenses/>.
#

name: VoxelOdysseyCore
version: '1.0.0'
main: com.guy7cc.voxelodyssey.core.VOCorePlugin
api-version: '1.21'

commands:
  voitem:
    description: Get custom items in Voxel Odyssey.
    permission: vo.command.voitem
    permission-message: You do not have permission to perform this command.

permissions:
  vo.command.voitem:
    description: Get custom items in Voxel Odyssey.
    default: op
